name: keepyoga

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  loading_indicator: ^3.1.1
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  icons_launcher: ^2.1.5
  names_launcher: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

names_launcher:
  name: "KeepYoga"
  platforms:
    android:
      enable: true
    ios:
      enable: true

icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/